import type { Food } from './types'
import { n } from './nutrients'

export const EXTRA_COOKIES: Food[] = [
  {
    id: 'subway-chocolate-chip',
    name: 'Subway Chocolate Chip Cookie',
    brand: 'Subway',
    category: 'cookies',
    servingLabel: '1 cookie (45 g)',
    increment: 1,
    nutrition: n({
      calories: 210,
      totalFatG: 10,
      saturatedFatG: 5,
      cholesterolMg: 10,
      sodiumMg: 120,
      carbsG: 30,
      fiberG: 0.5,
      totalSugarG: 18,
      addedSugarG: 18,
      proteinG: 2,
    }),
    source: {
      name: 'Subway US Nutrition Values — Chocolate Chip cookie',
      url: 'https://www.subway.com/',
      notes: 'Official US panel: 45 g cookie, 210 kcal, 10 g fat, 5 g sat. fat, 120 mg sodium, 30 g carb, 18 g sugars, 2 g protein.',
    },
    aliases: ['subway cookie', 'subway choc chip'],
  },
  {
    id: 'subway-oatmeal-raisin',
    name: 'Subway Oatmeal Raisin Cookie',
    brand: 'Subway',
    category: 'cookies',
    servingLabel: '1 cookie (45 g)',
    increment: 1,
    nutrition: n({
      calories: 200,
      totalFatG: 8,
      saturatedFatG: 4,
      cholesterolMg: 15,
      sodiumMg: 110,
      carbsG: 30,
      fiberG: 1,
      totalSugarG: 16,
      addedSugarG: 16,
      proteinG: 3,
    }),
    source: {
      name: 'Subway US Nutrition Values — Oatmeal Raisin cookie',
      url: 'https://www.subway.com/',
    },
    aliases: ['subway oatmeal'],
  },
  {
    id: 'subway-white-macadamia',
    name: 'Subway White Chip Macadamia Nut Cookie',
    brand: 'Subway',
    category: 'cookies',
    servingLabel: '1 cookie (45 g)',
    increment: 1,
    nutrition: n({
      calories: 210,
      totalFatG: 10,
      saturatedFatG: 5,
      cholesterolMg: 15,
      sodiumMg: 125,
      carbsG: 28,
      fiberG: 0.5,
      totalSugarG: 17,
      addedSugarG: 17,
      proteinG: 2,
    }),
    source: {
      name: 'Subway US Nutrition Values — White Chip Macadamia Nut cookie',
      url: 'https://www.subway.com/',
    },
    aliases: ['subway macadamia', 'white chocolate macadamia subway'],
  },
  {
    id: 'subway-raspberry-cheesecake',
    name: 'Subway Raspberry Cheesecake Cookie',
    brand: 'Subway',
    category: 'cookies',
    servingLabel: '1 cookie (45 g)',
    increment: 1,
    nutrition: n({
      calories: 210,
      totalFatG: 9,
      saturatedFatG: 5,
      cholesterolMg: 15,
      sodiumMg: 115,
      carbsG: 29,
      fiberG: 0,
      totalSugarG: 16,
      addedSugarG: 16,
      proteinG: 2,
    }),
    source: {
      name: 'Subway US Nutrition Values — Raspberry Cheesecake cookie',
      url: 'https://www.subway.com/',
    },
    aliases: ['subway raspberry'],
  },
  {
    id: 'mcdonalds-cookie',
    name: "McDonald's Chocolate Chip Cookie",
    brand: "McDonald's",
    category: 'cookies',
    servingLabel: '1 cookie',
    increment: 1,
    nutrition: n({
      calories: 170,
      totalFatG: 8,
      saturatedFatG: 4,
      cholesterolMg: 10,
      sodiumMg: 90,
      carbsG: 24,
      fiberG: 1,
      totalSugarG: 15,
      addedSugarG: 15,
      proteinG: 2,
    }),
    source: {
      name: "McDonald's Chocolate Chip Cookie nutrition (US menu)",
      url: 'https://www.mcdonalds.com/',
      notes: 'Typical US menu cookie: about 170 kcal and 15 g sugar per cookie. Values can vary slightly by bakery date.',
    },
    aliases: ['mcdonalds cookie', 'mcd cookie'],
  },
  {
    id: 'panera-chipper',
    name: 'Panera Chocolate Chipper Cookie',
    brand: 'Panera Bread',
    category: 'cookies',
    servingLabel: '1 cookie',
    increment: 1,
    nutrition: n({
      calories: 390,
      totalFatG: 19,
      saturatedFatG: 11,
      cholesterolMg: 50,
      sodiumMg: 290,
      carbsG: 52,
      fiberG: 2,
      totalSugarG: 31,
      addedSugarG: 31,
      proteinG: 4,
    }),
    source: {
      name: 'Panera Bread Chocolate Chipper Cookie nutrition',
      url: 'https://www.panerabread.com/',
    },
    aliases: ['panera cookie', 'chipper'],
  },
  {
    id: 'panera-kitchen-sink',
    name: 'Panera Kitchen Sink Cookie',
    brand: 'Panera Bread',
    category: 'cookies',
    servingLabel: '1 cookie',
    increment: 1,
    nutrition: n({
      calories: 800,
      totalFatG: 42,
      saturatedFatG: 23,
      cholesterolMg: 95,
      sodiumMg: 480,
      carbsG: 100,
      fiberG: 4,
      totalSugarG: 60,
      addedSugarG: 58,
      proteinG: 9,
    }),
    source: {
      name: 'Panera Bread Kitchen Sink Cookie (published menu calories)',
      url: 'https://www.panerabread.com/',
      notes: 'Very large bakery cookie. Calorie figure matches Panera menu guides (~800 kcal). Sugar/fat are estimated from typical bakery-cookie composition at that calorie level and published sugar (~60 g).',
    },
    aliases: ['kitchen sink cookie'],
  },
  {
    id: 'starbucks-chocolate-chip-cookie',
    name: 'Starbucks Chocolate Chip Cookie',
    brand: 'Starbucks',
    category: 'cookies',
    servingLabel: '1 cookie',
    increment: 1,
    nutrition: n({
      calories: 370,
      totalFatG: 18,
      saturatedFatG: 11,
      cholesterolMg: 40,
      sodiumMg: 250,
      carbsG: 51,
      fiberG: 2,
      totalSugarG: 31,
      addedSugarG: 31,
      proteinG: 5,
    }),
    source: {
      name: 'Starbucks Chocolate Chip Cookie nutrition',
      url: 'https://www.starbucks.com/',
    },
    aliases: ['starbucks cookie'],
  },
  {
    id: 'famous-amos',
    name: 'Famous Amos Chocolate Chip',
    brand: 'Famous Amos',
    category: 'cookies',
    servingLabel: '4 cookies (30 g)',
    increment: 1,
    nutrition: n({
      calories: 150,
      totalFatG: 7,
      saturatedFatG: 3,
      sodiumMg: 95,
      carbsG: 20,
      fiberG: 1,
      totalSugarG: 9,
      addedSugarG: 9,
      proteinG: 1,
    }),
    source: {
      name: 'Famous Amos Chocolate Chip Nutrition Facts',
      url: 'https://www.famousamos.com/',
    },
    aliases: ['famous amos'],
  },
  {
    id: 'pepperidge-milano',
    name: 'Pepperidge Farm Milano',
    brand: 'Pepperidge Farm',
    category: 'cookies',
    servingLabel: '3 cookies (26 g)',
    increment: 1,
    nutrition: n({
      calories: 140,
      totalFatG: 7,
      saturatedFatG: 4,
      cholesterolMg: 5,
      sodiumMg: 45,
      carbsG: 17,
      fiberG: 1,
      totalSugarG: 9,
      addedSugarG: 9,
      proteinG: 1,
    }),
    source: {
      name: 'Pepperidge Farm Milano Original Nutrition Facts',
      url: 'https://www.pepperidgefarm.com/',
    },
    aliases: ['milano'],
  },
  {
    id: 'nilla-wafers',
    name: 'Nilla Wafers',
    brand: 'Nabisco',
    category: 'cookies',
    servingLabel: '8 wafers (30 g)',
    increment: 1,
    nutrition: n({
      calories: 140,
      totalFatG: 4.5,
      saturatedFatG: 1,
      sodiumMg: 110,
      carbsG: 23,
      totalSugarG: 12,
      addedSugarG: 12,
      proteinG: 1,
    }),
    source: {
      name: 'Nabisco Nilla Wafers Nutrition Facts',
      url: 'https://www.nilla.com/',
    },
    aliases: ['nilla', 'vanilla wafers'],
  },
  {
    id: 'thin-mints',
    name: 'Girl Scout Thin Mints',
    brand: 'Girl Scouts',
    category: 'cookies',
    servingLabel: '4 cookies (28 g)',
    increment: 1,
    nutrition: n({
      calories: 160,
      totalFatG: 8,
      saturatedFatG: 6,
      sodiumMg: 115,
      carbsG: 22,
      fiberG: 1,
      totalSugarG: 12,
      addedSugarG: 12,
      proteinG: 1,
    }),
    source: {
      name: 'Girl Scout Thin Mints Nutrition Facts (Little Brownie Bakers)',
      url: 'https://www.girlscouts.org/',
    },
    aliases: ['thin mint', 'girl scout cookies'],
  },
  {
    id: 'samoa',
    name: 'Girl Scout Samoas / Caramel deLites',
    brand: 'Girl Scouts',
    category: 'cookies',
    servingLabel: '2 cookies (30 g)',
    increment: 1,
    nutrition: n({
      calories: 150,
      totalFatG: 8,
      saturatedFatG: 6,
      sodiumMg: 90,
      carbsG: 19,
      fiberG: 1,
      totalSugarG: 10,
      addedSugarG: 10,
      proteinG: 1,
    }),
    source: {
      name: 'Girl Scout Samoas / Caramel deLites Nutrition Facts',
      url: 'https://www.girlscouts.org/',
    },
    aliases: ['samoas', 'caramel delites'],
  },
  {
    id: 'keebler-fudge-stripes',
    name: 'Keebler Fudge Stripes',
    brand: 'Keebler',
    category: 'cookies',
    servingLabel: '2 cookies (31 g)',
    increment: 1,
    nutrition: n({
      calories: 150,
      totalFatG: 7,
      saturatedFatG: 4.5,
      sodiumMg: 90,
      carbsG: 22,
      fiberG: 1,
      totalSugarG: 11,
      addedSugarG: 11,
      proteinG: 1,
    }),
    source: {
      name: 'Keebler Fudge Stripes Nutrition Facts',
      url: 'https://www.keebler.com/',
    },
    aliases: ['fudge stripes'],
  },
  {
    id: 'oreo-double-stuf',
    name: 'Oreo Double Stuf',
    brand: 'Nabisco',
    category: 'cookies',
    servingLabel: '1 cookie',
    increment: 1,
    nutrition: n({
      calories: 70,
      totalFatG: 3,
      saturatedFatG: 1,
      sodiumMg: 45,
      carbsG: 10,
      totalSugarG: 6.5,
      addedSugarG: 6.5,
      proteinG: 0.5,
    }),
    source: {
      name: 'Nabisco Oreo Double Stuf Nutrition Facts',
      url: 'https://www.oreo.com/',
      notes: 'Label serving is typically 2 cookies / 70 g class: 140 kcal and 13 g added sugar. Per-cookie values are divided by 2.',
    },
    aliases: ['double stuff oreo', 'double stuf'],
  },
  {
    id: 'mrs-fields-chip',
    name: "Mrs. Fields Chocolate Chip Cookie",
    brand: 'Mrs. Fields',
    category: 'cookies',
    servingLabel: '1 cookie',
    increment: 1,
    nutrition: n({
      calories: 280,
      totalFatG: 14,
      saturatedFatG: 8,
      cholesterolMg: 30,
      sodiumMg: 180,
      carbsG: 37,
      fiberG: 1,
      totalSugarG: 22,
      addedSugarG: 22,
      proteinG: 3,
    }),
    source: {
      name: "Mrs. Fields original chocolate chip cookie (typical mall/bakery size)",
      notes: 'Bakery cookies vary by location. This is a representative original chocolate chip cookie, not a mini.',
    },
    aliases: ['mrs fields'],
  },
]
