import type { Food } from './types'
import { n } from './nutrients'

type MacroRow = {
  calories: number
  totalFatG: number
  saturatedFatG: number
  cholesterolMg: number
  sodiumMg: number
  carbsG: number
  totalSugarG: number
  addedSugarG: number
  proteinG: number
  fiberG?: number
}

function dessert(input: {
  id: string
  name: string
  brand?: string
  servingLabel: string
  increment?: number
  fractionalPortions?: boolean
  fluidMl?: number
  nutrition: MacroRow
  sourceName: string
  sourceUrl?: string
  notes?: string
  aliases?: string[]
}): Food {
  return {
    id: input.id,
    name: input.name,
    brand: input.brand,
    category: 'desserts',
    servingLabel: input.servingLabel,
    increment: input.increment ?? 0.5,
    fractionalPortions: input.fractionalPortions,
    fluidMl: input.fluidMl,
    nutrition: n({
      ...input.nutrition,
      fiberG: input.nutrition.fiberG ?? 0,
    }),
    source: {
      name: input.sourceName,
      url: input.sourceUrl,
      notes: input.notes,
    },
    aliases: input.aliases,
  }
}

function pint2_3(
  brand: string,
  flavor: string,
  id: string,
  row: MacroRow,
  sourceUrl: string,
  aliases: string[] = [],
): Food {
  return dessert({
    id,
    name: `${brand} ${flavor}`,
    brand,
    servingLabel: '⅔ cup (pint serving)',
    increment: 0.5,
    nutrition: row,
    sourceName: `${brand} ${flavor} — US pint label (⅔ cup serving)`,
    sourceUrl,
    notes: 'Standard US grocery pint serving. Log ½ serving if you ate half the scoop.',
    aliases: [`${brand.toLowerCase()} ${flavor.toLowerCase()}`, ...aliases],
  })
}

function bar(
  brand: string,
  name: string,
  id: string,
  servingLabel: string,
  row: MacroRow,
  sourceUrl: string,
  aliases: string[] = [],
): Food {
  return dessert({
    id,
    name: `${brand} ${name}`,
    brand,
    servingLabel,
    increment: 1,
    nutrition: row,
    sourceName: `${brand} ${name} — US package Nutrition Facts`,
    sourceUrl,
    aliases,
  })
}

const COLD_STONE_URL = 'https://www.coldstonecreamery.com/stores/menu'

type CsSize = 'like' | 'love' | 'gotta'

const CS_SIZE_META: Record<CsSize, { label: string; grams: number }> = {
  like: { label: 'Like It® (5 oz / 142 g)', grams: 142 },
  love: { label: 'Love It® (8 oz / 227 g)', grams: 227 },
  gotta: { label: 'Gotta Have It® (12 oz / 340 g)', grams: 340 },
}

function coldStone(
  flavor: string,
  slug: string,
  bySize: Record<CsSize, MacroRow>,
  aliases: string[] = [],
): Food[] {
  return (Object.keys(CS_SIZE_META) as CsSize[]).map((size) => {
    const meta = CS_SIZE_META[size]
    const row = bySize[size]
    return dessert({
      id: `coldstone-${slug}-${size}`,
      name: `Cold Stone ${flavor}`,
      brand: 'Cold Stone Creamery',
      servingLabel: meta.label,
      increment: 0.5,
      fractionalPortions: true,
      nutrition: row,
      sourceName: 'Cold Stone Creamery US menu nutrition (Like It / Love It / Gotta Have It)',
      sourceUrl: COLD_STONE_URL,
      notes: `Official Cold Stone size ${meta.label}. Gainesville / UF-area stores use the same sizes.`,
      aliases: [
        `cold stone ${flavor.toLowerCase()}`,
        `coldstone ${flavor.toLowerCase()}`,
        `${flavor.toLowerCase()} ${size}`,
        ...aliases,
      ],
    })
  })
}

/** Packaged pints, bars, chain treats, and Cold Stone — sugars from official US labels where available. */
export const EXTRA_ICE_CREAM: Food[] = [
  // —— Häagen-Dazs pints (⅔ cup) ——
  pint2_3(
    'Häagen-Dazs',
    'Vanilla',
    'hd-pint-vanilla',
    {
      calories: 320,
      totalFatG: 21,
      saturatedFatG: 13,
      cholesterolMg: 95,
      sodiumMg: 75,
      carbsG: 26,
      totalSugarG: 25,
      addedSugarG: 18,
      proteinG: 6,
    },
    'https://www.haagendazs.us/products/vanilla-ice-cream',
    ['haagen dazs vanilla', 'haagen-dazs vanilla'],
  ),
  pint2_3(
    'Häagen-Dazs',
    'Chocolate',
    'hd-pint-chocolate',
    {
      calories: 330,
      totalFatG: 21,
      saturatedFatG: 13,
      cholesterolMg: 90,
      sodiumMg: 80,
      carbsG: 28,
      totalSugarG: 26,
      addedSugarG: 19,
      proteinG: 6,
    },
    'https://www.haagendazs.us/products/chocolate-ice-cream',
    ['haagen dazs chocolate'],
  ),
  pint2_3(
    'Häagen-Dazs',
    'Strawberry',
    'hd-pint-strawberry',
    {
      calories: 310,
      totalFatG: 19,
      saturatedFatG: 12,
      cholesterolMg: 85,
      sodiumMg: 55,
      carbsG: 28,
      totalSugarG: 26,
      addedSugarG: 19,
      proteinG: 5,
    },
    'https://www.haagendazs.us/products/strawberry-ice-cream',
  ),
  pint2_3(
    'Häagen-Dazs',
    'Coffee',
    'hd-pint-coffee',
    {
      calories: 300,
      totalFatG: 19,
      saturatedFatG: 12,
      cholesterolMg: 85,
      sodiumMg: 60,
      carbsG: 27,
      totalSugarG: 24,
      addedSugarG: 17,
      proteinG: 5,
    },
    'https://www.haagendazs.us/products/coffee-ice-cream',
  ),
  pint2_3(
    'Häagen-Dazs',
    'Cookies & Cream',
    'hd-pint-cookies-cream',
    {
      calories: 340,
      totalFatG: 22,
      saturatedFatG: 14,
      cholesterolMg: 90,
      sodiumMg: 140,
      carbsG: 30,
      totalSugarG: 27,
      addedSugarG: 20,
      proteinG: 6,
    },
    'https://www.haagendazs.us/products/cookies-cream-ice-cream',
    ['haagen dazs cookies and cream'],
  ),
  pint2_3(
    'Häagen-Dazs',
    'Chocolate Peanut Butter',
    'hd-pint-choc-pb',
    {
      calories: 380,
      totalFatG: 26,
      saturatedFatG: 14,
      cholesterolMg: 90,
      sodiumMg: 150,
      carbsG: 30,
      totalSugarG: 26,
      addedSugarG: 20,
      proteinG: 8,
    },
    'https://www.haagendazs.us/products/chocolate-peanut-butter-ice-cream',
  ),

  // —— Häagen-Dazs bars ——
  bar(
    'Häagen-Dazs',
    'Vanilla Milk Chocolate Bar',
    'hd-bar-vanilla-choc',
    '1 bar (76 g)',
    {
      calories: 250,
      totalFatG: 18,
      saturatedFatG: 13,
      cholesterolMg: 45,
      sodiumMg: 40,
      carbsG: 20,
      totalSugarG: 19,
      addedSugarG: 15,
      proteinG: 3,
      fiberG: 1,
    },
    'https://www.haagendazs.us/products/vanilla-milk-chocolate-ice-cream-bar',
    ['haagen dazs bar', 'haagen dazs fudge bar', 'vanilla chocolate bar'],
  ),
  bar(
    'Häagen-Dazs',
    'Vanilla Milk Chocolate Almond Bar',
    'hd-bar-vanilla-almond',
    '1 bar (77 g)',
    {
      calories: 270,
      totalFatG: 19,
      saturatedFatG: 12,
      cholesterolMg: 40,
      sodiumMg: 40,
      carbsG: 20,
      totalSugarG: 18,
      addedSugarG: 14,
      proteinG: 4,
      fiberG: 1,
    },
    'https://www.haagendazs.us/products/vanilla-almond-ice-cream-bar',
    ['haagen dazs almond bar'],
  ),
  bar(
    'Häagen-Dazs',
    'Chocolate Dark Chocolate Bar',
    'hd-bar-choc-dark',
    '1 bar (76 g)',
    {
      calories: 280,
      totalFatG: 20,
      saturatedFatG: 14,
      cholesterolMg: 45,
      sodiumMg: 45,
      carbsG: 22,
      totalSugarG: 20,
      addedSugarG: 16,
      proteinG: 3,
      fiberG: 2,
    },
    'https://www.haagendazs.us/products/chocolate-dark-chocolate-ice-cream-bar',
  ),

  // —— Ben & Jerry's pints (⅔ cup / 141 g) ——
  pint2_3(
    "Ben & Jerry's",
    'Half Baked',
    'bj-half-baked',
    {
      calories: 370,
      totalFatG: 19,
      saturatedFatG: 12,
      cholesterolMg: 65,
      sodiumMg: 120,
      carbsG: 45,
      totalSugarG: 37,
      addedSugarG: 31,
      proteinG: 6,
      fiberG: 2,
    },
    'https://www.benjerry.com/flavors/half-baked-ice-cream',
    ['ben and jerrys half baked', 'ben jerry half baked'],
  ),
  pint2_3(
    "Ben & Jerry's",
    'Cherry Garcia',
    'bj-cherry-garcia',
    {
      calories: 330,
      totalFatG: 18,
      saturatedFatG: 11,
      cholesterolMg: 60,
      sodiumMg: 80,
      carbsG: 38,
      totalSugarG: 32,
      addedSugarG: 27,
      proteinG: 5,
      fiberG: 1,
    },
    'https://www.benjerry.com/flavors/cherry-garcia-ice-cream',
  ),
  pint2_3(
    "Ben & Jerry's",
    'Chocolate Fudge Brownie',
    'bj-choc-fudge-brownie',
    {
      calories: 380,
      totalFatG: 20,
      saturatedFatG: 12,
      cholesterolMg: 65,
      sodiumMg: 110,
      carbsG: 44,
      totalSugarG: 36,
      addedSugarG: 30,
      proteinG: 6,
      fiberG: 2,
    },
    'https://www.benjerry.com/flavors/chocolate-fudge-brownie-ice-cream',
    ['ben and jerrys brownie'],
  ),
  pint2_3(
    "Ben & Jerry's",
    'Phish Food',
    'bj-phish-food',
    {
      calories: 390,
      totalFatG: 20,
      saturatedFatG: 13,
      cholesterolMg: 60,
      sodiumMg: 150,
      carbsG: 47,
      totalSugarG: 42,
      addedSugarG: 36,
      proteinG: 6,
      fiberG: 2,
    },
    'https://www.benjerry.com/flavors/phish-food-ice-cream',
  ),
  pint2_3(
    "Ben & Jerry's",
    'Americone Dream',
    'bj-americone-dream',
    {
      calories: 340,
      totalFatG: 18,
      saturatedFatG: 11,
      cholesterolMg: 60,
      sodiumMg: 130,
      carbsG: 40,
      totalSugarG: 31,
      addedSugarG: 26,
      proteinG: 6,
      fiberG: 1,
    },
    'https://www.benjerry.com/flavors/americone-dream-ice-cream',
  ),
  pint2_3(
    "Ben & Jerry's",
    'Cookie Dough',
    'bj-cookie-dough',
    {
      calories: 360,
      totalFatG: 18,
      saturatedFatG: 11,
      cholesterolMg: 65,
      sodiumMg: 140,
      carbsG: 44,
      totalSugarG: 35,
      addedSugarG: 29,
      proteinG: 6,
      fiberG: 1,
    },
    'https://www.benjerry.com/flavors/chocolate-chip-cookie-dough-ice-cream',
    ['ben and jerrys cookie dough'],
  ),

  // —— Klondike bars ——
  bar(
    'Klondike',
    'The Original Bar',
    'klondike-original',
    '1 bar (85 g)',
    {
      calories: 250,
      totalFatG: 14,
      saturatedFatG: 11,
      cholesterolMg: 10,
      sodiumMg: 65,
      carbsG: 29,
      totalSugarG: 23,
      addedSugarG: 18,
      proteinG: 3,
      fiberG: 1,
    },
    'https://www.klondikebar.com/us/en/p/the-original-ice-cream-bar.html',
    ['klondike bar', 'klondike original'],
  ),
  bar(
    'Klondike',
    'Krunch Bar',
    'klondike-krunch',
    '1 bar (79 g)',
    {
      calories: 250,
      totalFatG: 14,
      saturatedFatG: 11,
      cholesterolMg: 10,
      sodiumMg: 70,
      carbsG: 29,
      totalSugarG: 22,
      addedSugarG: 17,
      proteinG: 3,
      fiberG: 1,
    },
    'https://www.klondikebar.com/',
    ['klondike krunch'],
  ),
  bar(
    'Klondike',
    'Reese\'s Bar',
    'klondike-reeses',
    '1 bar (85 g)',
    {
      calories: 290,
      totalFatG: 17,
      saturatedFatG: 11,
      cholesterolMg: 10,
      sodiumMg: 120,
      carbsG: 30,
      totalSugarG: 24,
      addedSugarG: 20,
      proteinG: 5,
      fiberG: 2,
    },
    'https://www.klondikebar.com/',
    ['klondike reeses', 'klondike peanut butter'],
  ),

  // —— Magnum ——
  bar(
    'Magnum',
    'Classic Bar',
    'magnum-classic',
    '1 bar (86 g)',
    {
      calories: 260,
      totalFatG: 16,
      saturatedFatG: 11,
      cholesterolMg: 25,
      sodiumMg: 52,
      carbsG: 27,
      totalSugarG: 23,
      addedSugarG: 18,
      proteinG: 3,
      fiberG: 1,
    },
    'https://www.magnumicecream.com/',
    ['magnum bar', 'magnum classic'],
  ),
  bar(
    'Magnum',
    'Double Caramel Bar',
    'magnum-double-caramel',
    '1 bar (85 g)',
    {
      calories: 290,
      totalFatG: 17,
      saturatedFatG: 12,
      cholesterolMg: 30,
      sodiumMg: 75,
      carbsG: 30,
      totalSugarG: 26,
      addedSugarG: 22,
      proteinG: 3,
      fiberG: 0,
    },
    'https://www.magnumicecream.com/',
    ['magnum caramel'],
  ),
  bar(
    'Magnum',
    'Almond Bar',
    'magnum-almond',
    '1 bar (86 g)',
    {
      calories: 270,
      totalFatG: 18,
      saturatedFatG: 12,
      cholesterolMg: 25,
      sodiumMg: 50,
      carbsG: 24,
      totalSugarG: 21,
      addedSugarG: 17,
      proteinG: 4,
      fiberG: 2,
    },
    'https://www.magnumicecream.com/',
  ),

  // —— Other grocery bars ——
  bar(
    'Drumstick',
    'Classic Vanilla Cone',
    'drumstick-classic',
    '1 cone (52 g)',
    {
      calories: 290,
      totalFatG: 16,
      saturatedFatG: 10,
      cholesterolMg: 15,
      sodiumMg: 75,
      carbsG: 34,
      totalSugarG: 17,
      addedSugarG: 15,
      proteinG: 4,
      fiberG: 1,
    },
    'https://www.drumstick.com/',
    ['drumstick', 'nestle drumstick'],
  ),
  bar(
    'Outshine',
    'Strawberry Fruit Bar',
    'outshine-strawberry',
    '1 bar (79 g)',
    {
      calories: 70,
      totalFatG: 0,
      saturatedFatG: 0,
      cholesterolMg: 0,
      sodiumMg: 0,
      carbsG: 17,
      totalSugarG: 15,
      addedSugarG: 12,
      proteinG: 0,
      fiberG: 1,
    },
    'https://www.outshine.com/',
    ['outshine bar', 'fruit bar'],
  ),
  bar(
    'Blue Bunny',
    'Bunny Tracks Bar',
    'blue-bunny-tracks',
    '1 bar (74 g)',
    {
      calories: 250,
      totalFatG: 14,
      saturatedFatG: 10,
      cholesterolMg: 10,
      sodiumMg: 70,
      carbsG: 28,
      totalSugarG: 22,
      addedSugarG: 18,
      proteinG: 3,
      fiberG: 1,
    },
    'https://www.bluebunny.com/',
    ['blue bunny bar'],
  ),

  // —— Chain / fast-food treats ——
  dessert({
    id: 'mcd-mcflurry-oreo',
    name: "McDonald's McFlurry with OREO",
    brand: "McDonald's",
    servingLabel: '1 regular McFlurry',
    increment: 0.5,
    nutrition: {
      calories: 510,
      totalFatG: 17,
      saturatedFatG: 9,
      cholesterolMg: 45,
      sodiumMg: 280,
      carbsG: 60,
      totalSugarG: 64,
      addedSugarG: 52,
      proteinG: 12,
      fiberG: 1,
    },
    sourceName: "McDonald's USA McFlurry with OREO nutrition",
    sourceUrl: 'https://www.mcdonalds.com/us/en-us/product/mcflurry-with-oreo-cookies.html',
    aliases: ['mcflurry', 'mcdonalds mcflurry'],
  }),
  dessert({
    id: 'mcd-hot-fudge-sundae',
    name: "McDonald's Hot Fudge Sundae",
    brand: "McDonald's",
    servingLabel: '1 sundae',
    nutrition: {
      calories: 330,
      totalFatG: 10,
      saturatedFatG: 6,
      cholesterolMg: 25,
      sodiumMg: 170,
      carbsG: 52,
      totalSugarG: 45,
      addedSugarG: 40,
      proteinG: 8,
    },
    sourceName: "McDonald's USA Hot Fudge Sundae nutrition",
    sourceUrl: 'https://www.mcdonalds.com/',
    aliases: ['mcdonalds sundae', 'hot fudge sundae'],
  }),
  dessert({
    id: 'mcd-vanilla-cone',
    name: "McDonald's Vanilla Cone",
    brand: "McDonald's",
    servingLabel: '1 cone',
    nutrition: {
      calories: 200,
      totalFatG: 5,
      saturatedFatG: 3,
      cholesterolMg: 15,
      sodiumMg: 80,
      carbsG: 33,
      totalSugarG: 23,
      addedSugarG: 20,
      proteinG: 5,
    },
    sourceName: "McDonald's USA Vanilla Cone nutrition",
    sourceUrl: 'https://www.mcdonalds.com/',
    aliases: ['mcdonalds cone', 'soft serve cone'],
  }),
  dessert({
    id: 'dq-oreo-blizzard-small',
    name: 'Dairy Queen Oreo Blizzard',
    brand: 'Dairy Queen',
    servingLabel: '1 small Blizzard',
    nutrition: {
      calories: 570,
      totalFatG: 21,
      saturatedFatG: 14,
      cholesterolMg: 60,
      sodiumMg: 320,
      carbsG: 83,
      totalSugarG: 65,
      addedSugarG: 55,
      proteinG: 12,
      fiberG: 1,
    },
    sourceName: 'Dairy Queen US Oreo Blizzard (small) nutrition',
    sourceUrl: 'https://www.dairyqueen.com/',
    aliases: ['dq blizzard', 'dairy queen blizzard', 'oreo blizzard'],
  }),
  dessert({
    id: 'dq-vanilla-cone-small',
    name: 'Dairy Queen Vanilla Cone',
    brand: 'Dairy Queen',
    servingLabel: '1 small cone',
    nutrition: {
      calories: 230,
      totalFatG: 7,
      saturatedFatG: 5,
      cholesterolMg: 25,
      sodiumMg: 95,
      carbsG: 37,
      totalSugarG: 32,
      addedSugarG: 28,
      proteinG: 6,
    },
    sourceName: 'Dairy Queen US small vanilla cone nutrition',
    sourceUrl: 'https://www.dairyqueen.com/',
    aliases: ['dq cone', 'dairy queen cone'],
  }),
  dessert({
    id: 'wendys-frosty-chocolate-small',
    name: "Wendy's Chocolate Frosty",
    brand: "Wendy's",
    servingLabel: '1 small Frosty',
    nutrition: {
      calories: 350,
      totalFatG: 9,
      saturatedFatG: 6,
      cholesterolMg: 35,
      sodiumMg: 190,
      carbsG: 58,
      totalSugarG: 47,
      addedSugarG: 42,
      proteinG: 9,
    },
    sourceName: "Wendy's US small Chocolate Frosty nutrition",
    sourceUrl: 'https://www.wendys.com/',
    aliases: ['wendys frosty', 'frosty'],
  }),

  // —— Cold Stone Creamery (UF / Gainesville locations) ——
  ...coldStone(
    'Sweet Cream',
    'sweet-cream',
    {
      like: { calories: 340, totalFatG: 21, saturatedFatG: 13, cholesterolMg: 80, sodiumMg: 115, carbsG: 36, totalSugarG: 33, addedSugarG: 28, proteinG: 5 },
      love: { calories: 540, totalFatG: 33, saturatedFatG: 21, cholesterolMg: 130, sodiumMg: 180, carbsG: 58, totalSugarG: 52, addedSugarG: 44, proteinG: 9 },
      gotta: { calories: 810, totalFatG: 50, saturatedFatG: 31, cholesterolMg: 195, sodiumMg: 270, carbsG: 86, totalSugarG: 78, addedSugarG: 66, proteinG: 13 },
    },
    ['cold stone sweet cream'],
  ),
  ...coldStone(
    'Cake Batter',
    'cake-batter',
    {
      like: { calories: 360, totalFatG: 19, saturatedFatG: 12, cholesterolMg: 75, sodiumMg: 180, carbsG: 44, totalSugarG: 36, addedSugarG: 30, proteinG: 5 },
      love: { calories: 580, totalFatG: 31, saturatedFatG: 19, cholesterolMg: 120, sodiumMg: 280, carbsG: 71, totalSugarG: 58, addedSugarG: 48, proteinG: 9 },
      gotta: { calories: 860, totalFatG: 46, saturatedFatG: 28, cholesterolMg: 175, sodiumMg: 420, carbsG: 106, totalSugarG: 86, addedSugarG: 72, proteinG: 13 },
    },
    ['cold stone cake batter', 'birthday cake batter'],
  ),
  ...coldStone(
    'Chocolate',
    'chocolate',
    {
      like: { calories: 330, totalFatG: 20, saturatedFatG: 13, cholesterolMg: 75, sodiumMg: 105, carbsG: 34, totalSugarG: 32, addedSugarG: 27, proteinG: 5 },
      love: { calories: 520, totalFatG: 31, saturatedFatG: 21, cholesterolMg: 120, sodiumMg: 170, carbsG: 54, totalSugarG: 51, addedSugarG: 43, proteinG: 9 },
      gotta: { calories: 780, totalFatG: 47, saturatedFatG: 31, cholesterolMg: 185, sodiumMg: 250, carbsG: 81, totalSugarG: 76, addedSugarG: 64, proteinG: 13 },
    },
  ),
  ...coldStone(
    'Strawberry',
    'strawberry',
    {
      like: { calories: 330, totalFatG: 19, saturatedFatG: 12, cholesterolMg: 75, sodiumMg: 105, carbsG: 37, totalSugarG: 34, addedSugarG: 29, proteinG: 5 },
      love: { calories: 520, totalFatG: 31, saturatedFatG: 19, cholesterolMg: 120, sodiumMg: 170, carbsG: 59, totalSugarG: 54, addedSugarG: 46, proteinG: 8 },
      gotta: { calories: 790, totalFatG: 46, saturatedFatG: 29, cholesterolMg: 180, sodiumMg: 250, carbsG: 89, totalSugarG: 80, addedSugarG: 68, proteinG: 12 },
    },
  ),
  ...coldStone(
    'Classic Cookie Dough',
    'cookie-dough',
    {
      like: { calories: 370, totalFatG: 18, saturatedFatG: 11, cholesterolMg: 70, sodiumMg: 220, carbsG: 50, totalSugarG: 38, addedSugarG: 32, proteinG: 6 },
      love: { calories: 590, totalFatG: 29, saturatedFatG: 18, cholesterolMg: 110, sodiumMg: 360, carbsG: 79, totalSugarG: 60, addedSugarG: 50, proteinG: 9 },
      gotta: { calories: 890, totalFatG: 43, saturatedFatG: 27, cholesterolMg: 165, sodiumMg: 540, carbsG: 119, totalSugarG: 90, addedSugarG: 76, proteinG: 13 },
    },
    ['cold stone cookie dough'],
  ),
  ...coldStone(
    'Mint',
    'mint',
    {
      like: { calories: 340, totalFatG: 20, saturatedFatG: 13, cholesterolMg: 80, sodiumMg: 110, carbsG: 38, totalSugarG: 33, addedSugarG: 28, proteinG: 5 },
      love: { calories: 550, totalFatG: 33, saturatedFatG: 20, cholesterolMg: 125, sodiumMg: 180, carbsG: 60, totalSugarG: 53, addedSugarG: 45, proteinG: 8 },
      gotta: { calories: 820, totalFatG: 49, saturatedFatG: 30, cholesterolMg: 190, sodiumMg: 270, carbsG: 91, totalSugarG: 79, addedSugarG: 67, proteinG: 13 },
    },
    ['cold stone mint', 'mint ice cream'],
  ),
  ...coldStone(
    'Chocolate Devotion',
    'chocolate-devotion',
    {
      like: { calories: 390, totalFatG: 22, saturatedFatG: 14, cholesterolMg: 80, sodiumMg: 200, carbsG: 44, totalSugarG: 40, addedSugarG: 34, proteinG: 6 },
      love: { calories: 620, totalFatG: 35, saturatedFatG: 22, cholesterolMg: 125, sodiumMg: 320, carbsG: 70, totalSugarG: 64, addedSugarG: 54, proteinG: 10 },
      gotta: { calories: 930, totalFatG: 52, saturatedFatG: 33, cholesterolMg: 185, sodiumMg: 480, carbsG: 105, totalSugarG: 96, addedSugarG: 81, proteinG: 15 },
    },
    ['cold stone devotion', 'chocolate devotion'],
  ),
]
