import type { Food } from './types'
import { n } from './nutrients'

export const EXTRA_CHOCOLATE: Food[] = [
  {
    id: 'hershey-kisses',
    name: "Hershey's Kisses Milk Chocolate",
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '9 pieces (41 g)',
    increment: 1,
    nutrition: n({
      calories: 200,
      totalFatG: 12,
      saturatedFatG: 7,
      cholesterolMg: 10,
      sodiumMg: 35,
      carbsG: 25,
      fiberG: 1,
      totalSugarG: 23,
      addedSugarG: 22,
      proteinG: 3,
    }),
    source: {
      name: "Hershey's Kisses Milk Chocolate Nutrition Facts",
      url: 'https://www.hersheyland.com/',
    },
    aliases: ['kisses', 'hershey kisses'],
  },
  {
    id: 'hershey-kisses-dark',
    name: "Hershey's Kisses Special Dark",
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '7 pieces (32 g)',
    increment: 1,
    nutrition: n({
      calories: 150,
      totalFatG: 10,
      saturatedFatG: 6,
      cholesterolMg: 5,
      sodiumMg: 0,
      carbsG: 20,
      fiberG: 2,
      totalSugarG: 17,
      addedSugarG: 17,
      proteinG: 2,
    }),
    source: {
      name: "Hershey's Kisses Special Dark Nutrition Facts",
      url: 'https://www.hersheyland.com/products/hersheys-kisses-special-dark-mildly-sweet-chocolate-candy-10-oz-pack.html',
    },
    aliases: ['dark kisses', 'special dark kisses'],
  },
  {
    id: 'hershey-special-dark-bar',
    name: "Hershey's Special Dark Bar",
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (41 g)',
    increment: 0.5,
    nutrition: n({
      calories: 190,
      totalFatG: 12,
      saturatedFatG: 8,
      cholesterolMg: 5,
      sodiumMg: 0,
      carbsG: 25,
      fiberG: 3,
      totalSugarG: 21,
      addedSugarG: 21,
      proteinG: 2,
    }),
    source: {
      name: "Hershey's Special Dark mildly sweet chocolate bar Nutrition Facts",
      url: 'https://www.hersheys.com/',
    },
    aliases: ['special dark', 'hershey dark'],
  },
  {
    id: 'hershey-almond-bar',
    name: "Hershey's Milk Chocolate with Almonds",
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (41 g)',
    increment: 0.5,
    nutrition: n({
      calories: 210,
      totalFatG: 14,
      saturatedFatG: 7,
      cholesterolMg: 10,
      sodiumMg: 25,
      carbsG: 21,
      fiberG: 2,
      totalSugarG: 19,
      addedSugarG: 18,
      proteinG: 4,
    }),
    source: {
      name: "Hershey's Milk Chocolate with Almonds Nutrition Facts",
      url: 'https://www.hersheys.com/',
    },
    aliases: ['hershey almond'],
  },
  {
    id: 'hershey-cookies-n-creme',
    name: "Hershey's Cookies 'n' Creme Bar",
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (43 g)',
    increment: 0.5,
    nutrition: n({
      calories: 220,
      totalFatG: 12,
      saturatedFatG: 7,
      cholesterolMg: 5,
      sodiumMg: 90,
      carbsG: 27,
      totalSugarG: 20,
      addedSugarG: 19,
      proteinG: 3,
    }),
    source: {
      name: "Hershey's Cookies 'n' Creme bar Nutrition Facts",
      url: 'https://www.hersheys.com/',
    },
    aliases: ['cookies and cream bar', 'cookies n creme'],
  },
  {
    id: 'hershey-symphony',
    name: "Hershey's Symphony",
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (42 g)',
    increment: 0.5,
    nutrition: n({
      calories: 220,
      totalFatG: 13,
      saturatedFatG: 8,
      cholesterolMg: 10,
      sodiumMg: 40,
      carbsG: 24,
      fiberG: 1,
      totalSugarG: 23,
      addedSugarG: 22,
      proteinG: 4,
    }),
    source: {
      name: "Hershey's Symphony milk chocolate bar Nutrition Facts",
      url: 'https://www.hersheys.com/',
    },
    aliases: ['symphony'],
  },
  {
    id: 'mr-goodbar',
    name: 'Mr. Goodbar',
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (49 g)',
    increment: 0.5,
    nutrition: n({
      calories: 270,
      totalFatG: 17,
      saturatedFatG: 8,
      cholesterolMg: 5,
      sodiumMg: 65,
      carbsG: 27,
      fiberG: 2,
      totalSugarG: 23,
      addedSugarG: 21,
      proteinG: 4,
    }),
    source: {
      name: "Hershey's Mr. Goodbar Nutrition Facts",
      url: 'https://www.hersheys.com/',
    },
    aliases: ['goodbar'],
  },
  {
    id: 'york-patty',
    name: 'York Peppermint Pattie',
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 pattie (39 g)',
    increment: 1,
    nutrition: n({
      calories: 150,
      totalFatG: 2.5,
      saturatedFatG: 1.5,
      sodiumMg: 10,
      carbsG: 31,
      fiberG: 1,
      totalSugarG: 25,
      addedSugarG: 25,
      proteinG: 1,
    }),
    source: {
      name: 'YORK Peppermint Pattie Nutrition Facts',
      url: 'https://www.yorkpeppermintpattie.com/',
    },
    aliases: ['york', 'peppermint pattie', 'peppermint patty'],
  },
  {
    id: 'almond-joy',
    name: 'Almond Joy',
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (45 g)',
    increment: 0.5,
    nutrition: n({
      calories: 220,
      totalFatG: 13,
      saturatedFatG: 8,
      cholesterolMg: 0,
      sodiumMg: 50,
      carbsG: 26,
      fiberG: 2,
      totalSugarG: 20,
      addedSugarG: 19,
      proteinG: 2,
    }),
    source: {
      name: 'Almond Joy Nutrition Facts',
      url: 'https://www.hersheys.com/',
    },
  },
  {
    id: 'mounds',
    name: 'Mounds',
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (49 g)',
    increment: 0.5,
    nutrition: n({
      calories: 230,
      totalFatG: 13,
      saturatedFatG: 10,
      sodiumMg: 45,
      carbsG: 28,
      fiberG: 3,
      totalSugarG: 21,
      addedSugarG: 21,
      proteinG: 2,
    }),
    source: {
      name: 'Mounds dark chocolate coconut bar Nutrition Facts',
      url: 'https://www.hersheys.com/',
    },
  },
  {
    id: 'heath-bar',
    name: 'Heath Bar',
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (39 g)',
    increment: 0.5,
    nutrition: n({
      calories: 210,
      totalFatG: 13,
      saturatedFatG: 7,
      cholesterolMg: 10,
      sodiumMg: 135,
      carbsG: 25,
      fiberG: 1,
      totalSugarG: 24,
      addedSugarG: 23,
      proteinG: 1,
    }),
    source: {
      name: 'HEATH English toffee bar Nutrition Facts',
      url: 'https://www.hersheys.com/',
    },
    aliases: ['heath'],
  },
  {
    id: 'payday',
    name: 'PayDay',
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (52 g)',
    increment: 0.5,
    nutrition: n({
      calories: 240,
      totalFatG: 13,
      saturatedFatG: 2.5,
      cholesterolMg: 0,
      sodiumMg: 220,
      carbsG: 27,
      fiberG: 2,
      totalSugarG: 21,
      addedSugarG: 20,
      proteinG: 7,
    }),
    source: {
      name: 'PAYDAY peanut caramel bar Nutrition Facts',
      url: 'https://www.hersheys.com/',
    },
  },
  {
    id: 'whatchamacallit',
    name: 'Whatchamacallit',
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (45 g)',
    increment: 0.5,
    nutrition: n({
      calories: 230,
      totalFatG: 11,
      saturatedFatG: 8,
      cholesterolMg: 5,
      sodiumMg: 140,
      carbsG: 30,
      fiberG: 1,
      totalSugarG: 24,
      addedSugarG: 23,
      proteinG: 3,
    }),
    source: {
      name: "Hershey's Whatchamacallit Nutrition Facts",
      url: 'https://www.hersheys.com/',
    },
  },
  {
    id: 'krackel',
    name: 'Krackel',
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (41 g)',
    increment: 0.5,
    nutrition: n({
      calories: 210,
      totalFatG: 13,
      saturatedFatG: 8,
      cholesterolMg: 5,
      sodiumMg: 35,
      carbsG: 24,
      fiberG: 1,
      totalSugarG: 22,
      addedSugarG: 21,
      proteinG: 3,
    }),
    source: {
      name: "Hershey's Krackel Nutrition Facts",
      url: 'https://www.hersheys.com/',
    },
  },
  {
    id: 'whoppers',
    name: 'Whoppers Malted Milk Balls',
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '18 pieces (41 g)',
    increment: 0.5,
    nutrition: n({
      calories: 190,
      totalFatG: 7,
      saturatedFatG: 7,
      cholesterolMg: 5,
      sodiumMg: 90,
      carbsG: 32,
      fiberG: 0,
      totalSugarG: 25,
      addedSugarG: 24,
      proteinG: 1,
    }),
    source: {
      name: 'WHOPPERS malted milk balls Nutrition Facts',
      url: 'https://www.hersheys.com/',
    },
    aliases: ['malted milk balls'],
  },
  {
    id: 'reeses-pieces',
    name: "Reese's Pieces",
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 serving (40 g)',
    increment: 0.5,
    nutrition: n({
      calories: 190,
      totalFatG: 9,
      saturatedFatG: 8,
      sodiumMg: 75,
      carbsG: 24,
      fiberG: 1,
      totalSugarG: 21,
      addedSugarG: 20,
      proteinG: 4,
    }),
    source: {
      name: "Reese's Pieces Nutrition Facts",
      url: 'https://www.reeses.com/',
    },
  },
  {
    id: 'milky-way',
    name: 'Milky Way',
    brand: 'Mars',
    category: 'chocolate_candy',
    servingLabel: '1 bar (52 g)',
    increment: 0.5,
    nutrition: n({
      calories: 240,
      totalFatG: 9,
      saturatedFatG: 7,
      cholesterolMg: 5,
      sodiumMg: 75,
      carbsG: 37,
      fiberG: 0.5,
      totalSugarG: 31,
      addedSugarG: 30,
      proteinG: 2,
    }),
    source: {
      name: 'Mars Milky Way Nutrition Facts',
      url: 'https://www.milkywaybar.com/',
    },
  },
  {
    id: 'three-musketeers',
    name: '3 Musketeers',
    brand: 'Mars',
    category: 'chocolate_candy',
    servingLabel: '1 bar (54 g)',
    increment: 0.5,
    nutrition: n({
      calories: 240,
      totalFatG: 7,
      saturatedFatG: 5,
      cholesterolMg: 5,
      sodiumMg: 100,
      carbsG: 42,
      fiberG: 1,
      totalSugarG: 36,
      addedSugarG: 35,
      proteinG: 2,
    }),
    source: {
      name: 'Mars 3 Musketeers Nutrition Facts',
      url: 'https://www.3musketeers.com/',
    },
    aliases: ['three musketeers'],
  },
  {
    id: 'butterfinger',
    name: 'Butterfinger',
    brand: 'Ferrero',
    category: 'chocolate_candy',
    servingLabel: '1 bar (60 g)',
    increment: 0.5,
    nutrition: n({
      calories: 270,
      totalFatG: 11,
      saturatedFatG: 6,
      sodiumMg: 150,
      carbsG: 43,
      fiberG: 1,
      totalSugarG: 28,
      addedSugarG: 27,
      proteinG: 3,
    }),
    source: {
      name: 'Butterfinger bar Nutrition Facts',
      url: 'https://www.butterfinger.com/',
    },
  },
  {
    id: 'baby-ruth',
    name: 'Baby Ruth',
    brand: 'Ferrero',
    category: 'chocolate_candy',
    servingLabel: '1 bar (60 g)',
    increment: 0.5,
    nutrition: n({
      calories: 280,
      totalFatG: 14,
      saturatedFatG: 8,
      cholesterolMg: 0,
      sodiumMg: 170,
      carbsG: 38,
      fiberG: 2,
      totalSugarG: 32,
      addedSugarG: 31,
      proteinG: 4,
    }),
    source: {
      name: 'Baby Ruth Nutrition Facts',
      url: 'https://www.babyruth.com/',
    },
  },
  {
    id: 'crunch-bar',
    name: 'Nestlé Crunch',
    brand: 'Nestlé / Ferrero',
    category: 'chocolate_candy',
    servingLabel: '1 bar (44 g)',
    increment: 0.5,
    nutrition: n({
      calories: 220,
      totalFatG: 11,
      saturatedFatG: 7,
      cholesterolMg: 5,
      sodiumMg: 50,
      carbsG: 28,
      fiberG: 1,
      totalSugarG: 24,
      addedSugarG: 23,
      proteinG: 2,
    }),
    source: {
      name: 'Crunch milk chocolate bar Nutrition Facts',
      url: 'https://www.crunchbar.com/',
    },
    aliases: ['crunch'],
  },
  {
    id: 'dove-milk',
    name: 'Dove Milk Chocolate Promises',
    brand: 'Mars',
    category: 'chocolate_candy',
    servingLabel: '5 pieces (38 g)',
    increment: 1,
    nutrition: n({
      calories: 200,
      totalFatG: 12,
      saturatedFatG: 8,
      cholesterolMg: 5,
      sodiumMg: 20,
      carbsG: 22,
      fiberG: 1,
      totalSugarG: 20,
      addedSugarG: 19,
      proteinG: 2,
    }),
    source: {
      name: 'DOVE Milk Chocolate Promises Nutrition Facts',
      url: 'https://www.dovechocolate.com/',
    },
    aliases: ['dove chocolate'],
  },
  {
    id: 'lindt-lindor',
    name: 'Lindt Lindor Milk Truffle',
    brand: 'Lindt',
    category: 'chocolate_candy',
    servingLabel: '3 truffles (36 g)',
    increment: 1,
    nutrition: n({
      calories: 220,
      totalFatG: 17,
      saturatedFatG: 12,
      cholesterolMg: 5,
      sodiumMg: 20,
      carbsG: 15,
      fiberG: 1,
      totalSugarG: 14,
      addedSugarG: 13,
      proteinG: 2,
    }),
    source: {
      name: 'Lindt Lindor Milk Chocolate Truffles Nutrition Facts',
      url: 'https://www.lindt.com/',
    },
    aliases: ['lindor', 'lindt'],
  },
  {
    id: 'ferrero-rocher',
    name: 'Ferrero Rocher',
    brand: 'Ferrero',
    category: 'chocolate_candy',
    servingLabel: '3 pieces (38 g)',
    increment: 1,
    nutrition: n({
      calories: 220,
      totalFatG: 16,
      saturatedFatG: 5.5,
      cholesterolMg: 5,
      sodiumMg: 20,
      carbsG: 17,
      fiberG: 1,
      totalSugarG: 15,
      addedSugarG: 14,
      proteinG: 3,
    }),
    source: {
      name: 'Ferrero Rocher Nutrition Facts',
      url: 'https://www.ferrerorocher.com/',
    },
    aliases: ['rocher'],
  },
  {
    id: 'cadbury-dairy-milk',
    name: 'Cadbury Dairy Milk',
    brand: 'Cadbury / Mondelez',
    category: 'chocolate_candy',
    servingLabel: '1 serving (40 g)',
    increment: 0.5,
    nutrition: n({
      calories: 210,
      totalFatG: 12,
      saturatedFatG: 7,
      cholesterolMg: 10,
      sodiumMg: 30,
      carbsG: 25,
      fiberG: 1,
      totalSugarG: 24,
      addedSugarG: 23,
      proteinG: 3,
    }),
    source: {
      name: 'Cadbury Dairy Milk Nutrition Facts (typical 40 g bar serving)',
      url: 'https://www.cadbury.com/',
    },
    aliases: ['cadbury', 'dairy milk'],
  },
  {
    id: 'toblerone',
    name: 'Toblerone',
    brand: 'Mondelez',
    category: 'chocolate_candy',
    servingLabel: '1 serving (35 g, about 3 peaks)',
    increment: 1,
    nutrition: n({
      calories: 190,
      totalFatG: 11,
      saturatedFatG: 6,
      cholesterolMg: 5,
      sodiumMg: 20,
      carbsG: 21,
      fiberG: 1,
      totalSugarG: 20,
      addedSugarG: 19,
      proteinG: 2,
    }),
    source: {
      name: 'Toblerone Milk Chocolate Nutrition Facts',
      url: 'https://www.toblerone.com/',
    },
  },
  {
    id: 'ghirardelli-square',
    name: 'Ghirardelli Milk Chocolate Square',
    brand: 'Ghirardelli',
    category: 'chocolate_candy',
    servingLabel: '3 squares (38 g)',
    increment: 1,
    nutrition: n({
      calories: 210,
      totalFatG: 13,
      saturatedFatG: 8,
      cholesterolMg: 10,
      sodiumMg: 25,
      carbsG: 22,
      fiberG: 1,
      totalSugarG: 20,
      addedSugarG: 19,
      proteinG: 3,
    }),
    source: {
      name: 'Ghirardelli milk chocolate squares Nutrition Facts',
      url: 'https://www.ghirardelli.com/',
    },
    aliases: ['ghirardelli'],
  },
]
