import type { Food } from './types'
import { EXTRA_CHOCOLATE } from './catalog-chocolate'
import { EXTRA_COOKIES } from './catalog-cookies'
import { EXTRA_DRINKS } from './catalog-drinks'
import { n } from './nutrients'

export const FOOD_CATALOG: Food[] = [
  {
    id: 'oreo-original',
    name: 'Oreo',
    brand: 'Nabisco',
    category: 'cookies',
    servingLabel: '1 cookie',
    increment: 1,
    nutrition: n({
      calories: 160 / 3,
      totalFatG: 7 / 3,
      saturatedFatG: 2 / 3,
      sodiumMg: 90 / 3,
      carbsG: 25 / 3,
      fiberG: 0.3,
      totalSugarG: 14 / 3,
      addedSugarG: 14 / 3,
      proteinG: 1 / 3,
    }),
    source: {
      name: 'Nabisco Oreo Original Nutrition Facts',
      url: 'https://www.oreo.com/',
      notes: 'Label serving is 3 cookies (34 g): 160 kcal, 7 g fat, 2 g sat. fat, 90 mg sodium, 25 g carb, 14 g added sugar, 1 g protein. Values here are divided by 3 so you can log individual cookies.',
    },
    aliases: ['oreos', 'oreo cookie'],
  },
  {
    id: 'chickfila-cookie',
    name: 'Chick-fil-A Chocolate Chunk Cookie',
    brand: 'Chick-fil-A',
    category: 'cookies',
    servingLabel: '1 cookie',
    increment: 1,
    nutrition: n({
      calories: 370,
      totalFatG: 17,
      saturatedFatG: 9,
      cholesterolMg: 15,
      sodiumMg: 230,
      carbsG: 49,
      fiberG: 3,
      totalSugarG: 26,
      addedSugarG: 26,
      proteinG: 5,
    }),
    source: {
      name: 'Chick-fil-A Chocolate Chunk Cookie nutrition',
      url: 'https://www.chick-fil-a.com/menu/treats/chocolate-chunk-cookie',
      notes: 'Official menu: 370 kcal, 17 g fat, 49 g carb, 5 g protein. Saturated fat 9 g, sodium 230 mg, sugars 26 g from published nutrition panels. Added sugar is not listed separately; 26 g is used as an added-sugar estimate because the ingredient list is dominated by added sugars.',
    },
    aliases: ['cfa cookie', 'chick fil a cookie'],
  },
  {
    id: 'chips-ahoy',
    name: 'Chips Ahoy! Original',
    brand: 'Nabisco',
    category: 'cookies',
    servingLabel: '1 cookie',
    increment: 1,
    nutrition: n({
      calories: 160 / 3,
      totalFatG: 8 / 3,
      saturatedFatG: 2.5 / 3,
      sodiumMg: 110 / 3,
      carbsG: 22 / 3,
      fiberG: 1 / 3,
      totalSugarG: 11 / 3,
      addedSugarG: 11 / 3,
      proteinG: 2 / 3,
    }),
    source: {
      name: 'Nabisco Chips Ahoy! Original Nutrition Facts',
      url: 'https://www.chipsahoy.com/',
      notes: 'Typical US label serving 3 cookies: 160 kcal, 8 g fat, 2.5 g sat. fat, 110 mg sodium, 11 g added sugar. Per-cookie values are divided by 3.',
    },
    aliases: ['chips ahoy', 'chocolate chip cookie packaged'],
  },
  {
    id: 'chocolate-chip-cookie',
    name: 'Chocolate chip cookie',
    brand: 'Typical bakery / homemade',
    category: 'cookies',
    servingLabel: '1 medium cookie (30 g)',
    increment: 1,
    nutrition: n({
      calories: 148,
      totalFatG: 7.4,
      saturatedFatG: 2.3,
      cholesterolMg: 9,
      sodiumMg: 92,
      carbsG: 19.6,
      fiberG: 0.6,
      totalSugarG: 9.8,
      addedSugarG: 9.5,
      proteinG: 1.6,
    }),
    source: {
      name: 'USDA FoodData Central — cookies, chocolate chip, commercially prepared',
      url: 'https://fdc.nal.usda.gov/',
      notes: 'Approximate medium (30 g) commercial chocolate chip cookie from USDA FoodData Central. Added sugar estimated from total sugar for this product type.',
    },
    aliases: ['choc chip', 'homemade cookie'],
  },
  {
    id: 'nutter-butter',
    name: 'Nutter Butter',
    brand: 'Nabisco',
    category: 'cookies',
    servingLabel: '1 cookie',
    increment: 1,
    nutrition: n({
      calories: 130 / 2,
      totalFatG: 5 / 2,
      saturatedFatG: 1 / 2,
      sodiumMg: 90 / 2,
      carbsG: 19 / 2,
      fiberG: 0.5,
      totalSugarG: 8 / 2,
      addedSugarG: 8 / 2,
      proteinG: 2 / 2,
    }),
    source: {
      name: 'Nabisco Nutter Butter Nutrition Facts',
      notes: 'Label serving is typically 2 cookies: 130 kcal, 5 g fat, 8 g sugars. Per-cookie values are divided by 2.',
    },
  },
  {
    id: 'sugar-cookie',
    name: 'Sugar cookie',
    category: 'cookies',
    servingLabel: '1 cookie (30 g)',
    increment: 1,
    nutrition: n({
      calories: 132,
      totalFatG: 5.6,
      saturatedFatG: 1.4,
      cholesterolMg: 8,
      sodiumMg: 90,
      carbsG: 18.5,
      fiberG: 0.3,
      totalSugarG: 8.4,
      addedSugarG: 8.4,
      proteinG: 1.4,
    }),
    source: {
      name: 'USDA FoodData Central — cookies, sugar, commercially prepared',
      url: 'https://fdc.nal.usda.gov/',
    },
  },
  {
    id: 'mms-milk',
    name: "M&M's Milk Chocolate",
    brand: 'Mars',
    category: 'chocolate_candy',
    servingLabel: '1 serving (42 g, about 48 pieces)',
    increment: 0.5,
    nutrition: n({
      calories: 200,
      totalFatG: 8,
      saturatedFatG: 5,
      sodiumMg: 25,
      carbsG: 30,
      fiberG: 1,
      totalSugarG: 27,
      addedSugarG: 26,
      proteinG: 2,
    }),
    source: {
      name: "Mars M&M's Milk Chocolate Nutrition Facts",
      url: 'https://www.mms.com/',
      notes: 'Standard 1.5 oz / 42 g sharing-size serving on US packaging.',
    },
    aliases: ['mms', 'm and ms'],
  },
  {
    id: 'snickers',
    name: 'Snickers',
    brand: 'Mars',
    category: 'chocolate_candy',
    servingLabel: '1 bar (52.7 g)',
    increment: 0.5,
    nutrition: n({
      calories: 250,
      totalFatG: 12,
      saturatedFatG: 4.5,
      cholesterolMg: 5,
      sodiumMg: 120,
      carbsG: 33,
      fiberG: 1,
      totalSugarG: 27,
      addedSugarG: 25,
      proteinG: 4,
    }),
    source: {
      name: 'Mars Snickers bar Nutrition Facts',
      url: 'https://www.snickers.com/',
    },
  },
  {
    id: 'kitkat',
    name: 'KitKat',
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 four-finger bar (42 g)',
    increment: 0.5,
    nutrition: n({
      calories: 210,
      totalFatG: 11,
      saturatedFatG: 7,
      cholesterolMg: 5,
      sodiumMg: 30,
      carbsG: 27,
      fiberG: 1,
      totalSugarG: 21,
      addedSugarG: 20,
      proteinG: 3,
    }),
    source: {
      name: 'The Hershey Company KitKat Nutrition Facts',
      url: 'https://www.kitkat.com/',
    },
    aliases: ['kit kat'],
  },
  {
    id: 'hershey-bar',
    name: "Hershey's Milk Chocolate Bar",
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '1 bar (43 g)',
    increment: 0.5,
    nutrition: n({
      calories: 220,
      totalFatG: 13,
      saturatedFatG: 8,
      cholesterolMg: 10,
      sodiumMg: 35,
      carbsG: 24,
      fiberG: 1,
      totalSugarG: 22,
      addedSugarG: 21,
      proteinG: 3,
    }),
    source: {
      name: "Hershey's Milk Chocolate bar Nutrition Facts",
      url: 'https://www.hersheys.com/',
    },
  },
  {
    id: 'reeses',
    name: "Reese's Peanut Butter Cups",
    brand: 'Hershey',
    category: 'chocolate_candy',
    servingLabel: '2 cups (42 g)',
    increment: 0.5,
    nutrition: n({
      calories: 210,
      totalFatG: 13,
      saturatedFatG: 4.5,
      cholesterolMg: 5,
      sodiumMg: 150,
      carbsG: 24,
      fiberG: 1,
      totalSugarG: 21,
      addedSugarG: 20,
      proteinG: 5,
    }),
    source: {
      name: "Hershey's Reese's Peanut Butter Cups Nutrition Facts",
      url: 'https://www.reeses.com/',
    },
    aliases: ['reese', 'peanut butter cups'],
  },
  {
    id: 'gummy-bears',
    name: 'Gummy bears',
    category: 'chocolate_candy',
    servingLabel: '1 serving (30 g, about 10 pieces)',
    increment: 0.5,
    nutrition: n({
      calories: 100,
      totalFatG: 0,
      sodiumMg: 15,
      carbsG: 24,
      totalSugarG: 18,
      addedSugarG: 18,
      proteinG: 2,
    }),
    source: {
      name: 'USDA FoodData Central — candies, gumdrops, starch jelly pieces',
      url: 'https://fdc.nal.usda.gov/',
    },
    aliases: ['gummies'],
  },
  {
    id: 'skittles',
    name: 'Skittles',
    brand: 'Mars',
    category: 'chocolate_candy',
    servingLabel: '1 serving (40 g)',
    increment: 0.5,
    nutrition: n({
      calories: 160,
      totalFatG: 1.5,
      saturatedFatG: 1.5,
      sodiumMg: 5,
      carbsG: 37,
      totalSugarG: 30,
      addedSugarG: 30,
      proteinG: 0,
    }),
    source: {
      name: 'Mars Skittles Original Nutrition Facts',
      url: 'https://www.skittles.com/',
    },
  },
  {
    id: 'twix',
    name: 'Twix',
    brand: 'Mars',
    category: 'chocolate_candy',
    servingLabel: '1 package (2 bars, 51 g)',
    increment: 0.5,
    nutrition: n({
      calories: 250,
      totalFatG: 12,
      saturatedFatG: 7,
      cholesterolMg: 5,
      sodiumMg: 100,
      carbsG: 34,
      fiberG: 1,
      totalSugarG: 24,
      addedSugarG: 23,
      proteinG: 2,
    }),
    source: {
      name: 'Mars Twix Nutrition Facts',
      url: 'https://www.twix.com/',
    },
  },
  {
    id: 'mcdonalds-fries-medium',
    name: "McDonald's French Fries",
    brand: "McDonald's",
    category: 'fast_food',
    servingLabel: '1 medium',
    increment: 0.5,
    nutrition: n({
      calories: 320,
      totalFatG: 15,
      saturatedFatG: 2,
      transFatG: 0,
      sodiumMg: 260,
      carbsG: 43,
      fiberG: 4,
      totalSugarG: 0,
      addedSugarG: 0,
      proteinG: 5,
    }),
    source: {
      name: "McDonald's USA Medium French Fries nutrition",
      url: 'https://www.mcdonalds.com/us/en-us/product/medium-french-fries.html',
    },
    aliases: ['fries', 'mcdonalds fries', 'french fries'],
  },
  {
    id: 'mcdonalds-big-mac',
    name: 'Big Mac',
    brand: "McDonald's",
    category: 'fast_food',
    servingLabel: '1 sandwich',
    increment: 0.5,
    nutrition: n({
      calories: 590,
      totalFatG: 34,
      saturatedFatG: 11,
      transFatG: 1,
      cholesterolMg: 85,
      sodiumMg: 1050,
      carbsG: 46,
      fiberG: 3,
      totalSugarG: 9,
      addedSugarG: 6,
      proteinG: 25,
    }),
    source: {
      name: "McDonald's USA Big Mac nutrition",
      url: 'https://www.mcdonalds.com/us/en-us/product/big-mac.html',
    },
    aliases: ['bigmac', 'burger'],
  },
  {
    id: 'mcdonalds-nuggets-6',
    name: "McDonald's Chicken McNuggets",
    brand: "McDonald's",
    category: 'fast_food',
    servingLabel: '6 pieces',
    increment: 0.5,
    nutrition: n({
      calories: 250,
      totalFatG: 15,
      saturatedFatG: 2.5,
      cholesterolMg: 40,
      sodiumMg: 500,
      carbsG: 15,
      fiberG: 1,
      totalSugarG: 0,
      addedSugarG: 0,
      proteinG: 14,
    }),
    source: {
      name: "McDonald's USA 6-piece Chicken McNuggets nutrition",
      url: 'https://www.mcdonalds.com/us/en-us/product/chicken-mcnuggets-6-piece.html',
    },
    aliases: ['nuggets', 'mcnuggets'],
  },
  {
    id: 'cfa-chicken-sandwich',
    name: 'Chick-fil-A Chicken Sandwich',
    brand: 'Chick-fil-A',
    category: 'fast_food',
    servingLabel: '1 sandwich',
    increment: 0.5,
    nutrition: n({
      calories: 440,
      totalFatG: 18,
      saturatedFatG: 3.5,
      cholesterolMg: 60,
      sodiumMg: 1410,
      carbsG: 41,
      fiberG: 2,
      totalSugarG: 6,
      addedSugarG: 5,
      proteinG: 28,
    }),
    source: {
      name: 'Chick-fil-A Chicken Sandwich nutrition',
      url: 'https://www.chick-fil-a.com/menu/chick-fil-a-chicken-sandwich',
    },
  },
  {
    id: 'cfa-waffle-fries-medium',
    name: 'Chick-fil-A Waffle Potato Fries',
    brand: 'Chick-fil-A',
    category: 'fast_food',
    servingLabel: '1 medium',
    increment: 0.5,
    nutrition: n({
      calories: 420,
      totalFatG: 24,
      saturatedFatG: 3.5,
      sodiumMg: 240,
      carbsG: 45,
      fiberG: 5,
      totalSugarG: 1,
      addedSugarG: 0,
      proteinG: 5,
    }),
    source: {
      name: 'Chick-fil-A medium Waffle Potato Fries nutrition',
      url: 'https://www.chick-fil-a.com/menu/waffle-potato-fries',
    },
    aliases: ['waffle fries', 'cfa fries'],
  },
  {
    id: 'whopper',
    name: 'Whopper',
    brand: 'Burger King',
    category: 'fast_food',
    servingLabel: '1 sandwich',
    increment: 0.5,
    nutrition: n({
      calories: 670,
      totalFatG: 40,
      saturatedFatG: 12,
      transFatG: 1.5,
      cholesterolMg: 90,
      sodiumMg: 980,
      carbsG: 51,
      fiberG: 2,
      totalSugarG: 11,
      addedSugarG: 7,
      proteinG: 31,
    }),
    source: {
      name: 'Burger King Whopper nutrition',
      url: 'https://www.bk.com/menu/picker-whopper',
    },
  },
  {
    id: 'pepperoni-pizza-slice',
    name: 'Pepperoni pizza slice',
    category: 'fast_food',
    servingLabel: '1 slice (large, 1/8 pie)',
    increment: 0.5,
    nutrition: n({
      calories: 298,
      totalFatG: 12.3,
      saturatedFatG: 5.2,
      cholesterolMg: 27,
      sodiumMg: 680,
      carbsG: 33.6,
      fiberG: 2.3,
      totalSugarG: 3.6,
      addedSugarG: 2,
      proteinG: 12.2,
    }),
    source: {
      name: 'USDA FoodData Central — pizza, pepperoni topping, regular crust',
      url: 'https://fdc.nal.usda.gov/',
    },
    aliases: ['pizza'],
  },
  {
    id: 'crunchy-taco',
    name: 'Crunchy taco',
    brand: 'Taco Bell',
    category: 'fast_food',
    servingLabel: '1 taco',
    increment: 1,
    nutrition: n({
      calories: 170,
      totalFatG: 9,
      saturatedFatG: 3.5,
      cholesterolMg: 25,
      sodiumMg: 310,
      carbsG: 13,
      fiberG: 3,
      totalSugarG: 1,
      addedSugarG: 0,
      proteinG: 8,
    }),
    source: {
      name: 'Taco Bell Crunchy Taco nutrition',
      url: 'https://www.tacobell.com/',
    },
  },
  {
    id: 'coke-12',
    name: 'Coca-Cola Classic',
    brand: 'Coca-Cola',
    category: 'sugary_drinks',
    servingLabel: '12 fl oz can (355 mL)',
    increment: 0.5,
    nutrition: n({
      calories: 140,
      sodiumMg: 45,
      carbsG: 39,
      totalSugarG: 39,
      addedSugarG: 39,
    }),
    source: {
      name: 'The Coca-Cola Company — 12 fl oz Coca-Cola Nutrition Facts',
      url: 'https://www.coca-cola.com/us/en/offerings/coca-cola',
    },
    aliases: ['coke', 'cola', 'soda', 'coca cola', 'cocacola', 'cocoola'],
  },
  {
    id: 'pepsi-12',
    name: 'Pepsi',
    brand: 'PepsiCo',
    category: 'sugary_drinks',
    servingLabel: '12 fl oz can (355 mL)',
    increment: 0.5,
    nutrition: n({
      calories: 150,
      sodiumMg: 30,
      carbsG: 41,
      totalSugarG: 41,
      addedSugarG: 41,
    }),
    source: {
      name: 'PepsiCo Pepsi 12 fl oz Nutrition Facts',
      url: 'https://www.pepsi.com/',
    },
  },
  {
    id: 'sprite-12',
    name: 'Sprite',
    brand: 'Coca-Cola',
    category: 'sugary_drinks',
    servingLabel: '12 fl oz can (355 mL)',
    increment: 0.5,
    nutrition: n({
      calories: 140,
      sodiumMg: 65,
      carbsG: 38,
      totalSugarG: 38,
      addedSugarG: 38,
    }),
    source: {
      name: 'Sprite 12 fl oz Nutrition Facts',
      url: 'https://www.sprite.com/',
    },
  },
  {
    id: 'mountain-dew-12',
    name: 'Mountain Dew',
    brand: 'PepsiCo',
    category: 'sugary_drinks',
    servingLabel: '12 fl oz can (355 mL)',
    increment: 0.5,
    nutrition: n({
      calories: 170,
      sodiumMg: 60,
      carbsG: 46,
      totalSugarG: 46,
      addedSugarG: 46,
    }),
    source: {
      name: 'Mountain Dew 12 fl oz Nutrition Facts',
      url: 'https://www.mountaindew.com/',
    },
    aliases: ['dew'],
  },
  {
    id: 'sweet-tea-16',
    name: 'Sweet tea',
    category: 'sugary_drinks',
    servingLabel: '16 fl oz',
    increment: 0.5,
    nutrition: n({
      calories: 180,
      sodiumMg: 15,
      carbsG: 45,
      totalSugarG: 45,
      addedSugarG: 45,
    }),
    source: {
      name: 'USDA FoodData Central — tea, sweetened, ready-to-drink (approximate 16 fl oz)',
      url: 'https://fdc.nal.usda.gov/',
      notes: 'Restaurant sweet teas vary widely. This is a typical 16 fl oz sweetened black tea.',
    },
    aliases: ['iced tea', 'sweetened tea'],
  },
  {
    id: 'redbull-84',
    name: 'Red Bull',
    brand: 'Red Bull',
    category: 'sugary_drinks',
    servingLabel: '8.4 fl oz can',
    increment: 0.5,
    nutrition: n({
      calories: 110,
      sodiumMg: 105,
      carbsG: 28,
      totalSugarG: 27,
      addedSugarG: 27,
    }),
    source: {
      name: 'Red Bull Energy Drink 8.4 fl oz Nutrition Facts',
      url: 'https://www.redbull.com/',
    },
    aliases: ['energy drink'],
  },
  {
    id: 'gatorade-12',
    name: 'Gatorade Thirst Quencher',
    brand: 'PepsiCo',
    category: 'sugary_drinks',
    servingLabel: '12 fl oz',
    increment: 0.5,
    nutrition: n({
      calories: 80,
      sodiumMg: 160,
      carbsG: 21,
      totalSugarG: 21,
      addedSugarG: 21,
    }),
    source: {
      name: 'Gatorade Orange 12 fl oz Nutrition Facts',
      url: 'https://www.gatorade.com/',
    },
    aliases: ['sports drink'],
  },
  {
    id: 'sweet-coffee-16',
    name: 'Sweetened coffee drink',
    category: 'sugary_drinks',
    servingLabel: '16 fl oz (grande-style)',
    increment: 0.5,
    nutrition: n({
      calories: 250,
      totalFatG: 4,
      saturatedFatG: 2.5,
      cholesterolMg: 15,
      sodiumMg: 150,
      carbsG: 43,
      totalSugarG: 40,
      addedSugarG: 32,
      proteinG: 10,
    }),
    source: {
      name: 'Typical 16 fl oz flavored latte / sweetened coffee (manufacturer menus vary)',
      notes: 'Coffee drinks vary by milk, syrup pumps, and size. This is a representative 16 fl oz sweetened coffee beverage, not a specific branded recipe.',
    },
    aliases: ['latte', 'frappuccino', 'sweet coffee'],
  },
  {
    id: 'vanilla-ice-cream',
    name: 'Vanilla ice cream',
    category: 'desserts',
    servingLabel: '½ cup (66 g)',
    increment: 0.5,
    nutrition: n({
      calories: 137,
      totalFatG: 7.3,
      saturatedFatG: 4.5,
      cholesterolMg: 29,
      sodiumMg: 53,
      carbsG: 15.6,
      fiberG: 0.5,
      totalSugarG: 14,
      addedSugarG: 12,
      proteinG: 2.3,
    }),
    source: {
      name: 'USDA FoodData Central — ice cream, vanilla',
      url: 'https://fdc.nal.usda.gov/',
    },
    aliases: ['ice cream'],
  },
  {
    id: 'chocolate-ice-cream',
    name: 'Chocolate ice cream',
    category: 'desserts',
    servingLabel: '½ cup (66 g)',
    increment: 0.5,
    nutrition: n({
      calories: 143,
      totalFatG: 7.3,
      saturatedFatG: 4.5,
      cholesterolMg: 22,
      sodiumMg: 50,
      carbsG: 18.6,
      fiberG: 0.8,
      totalSugarG: 16.7,
      addedSugarG: 14,
      proteinG: 2.5,
    }),
    source: {
      name: 'USDA FoodData Central — ice cream, chocolate',
      url: 'https://fdc.nal.usda.gov/',
    },
  },
  {
    id: 'glazed-donut',
    name: 'Glazed donut',
    category: 'desserts',
    servingLabel: '1 donut (about 60 g)',
    increment: 0.5,
    nutrition: n({
      calories: 240,
      totalFatG: 14,
      saturatedFatG: 6,
      cholesterolMg: 5,
      sodiumMg: 210,
      carbsG: 27,
      fiberG: 0.7,
      totalSugarG: 12,
      addedSugarG: 12,
      proteinG: 3,
    }),
    source: {
      name: 'USDA FoodData Central — doughnuts, yeast-leavened, glazed',
      url: 'https://fdc.nal.usda.gov/',
    },
    aliases: ['doughnut', 'donut'],
  },
  {
    id: 'brownie',
    name: 'Brownie',
    category: 'desserts',
    servingLabel: '1 square (2 inch, 56 g)',
    increment: 0.5,
    nutrition: n({
      calories: 227,
      totalFatG: 9,
      saturatedFatG: 2.2,
      cholesterolMg: 10,
      sodiumMg: 160,
      carbsG: 36,
      fiberG: 1.2,
      totalSugarG: 20,
      addedSugarG: 20,
      proteinG: 2.7,
    }),
    source: {
      name: 'USDA FoodData Central — cookies, brownies, commercially prepared',
      url: 'https://fdc.nal.usda.gov/',
    },
  },
  {
    id: 'chocolate-cake',
    name: 'Chocolate cake',
    category: 'desserts',
    servingLabel: '1 slice (80 g)',
    increment: 0.5,
    nutrition: n({
      calories: 280,
      totalFatG: 12,
      saturatedFatG: 3.5,
      cholesterolMg: 35,
      sodiumMg: 250,
      carbsG: 41,
      fiberG: 2,
      totalSugarG: 28,
      addedSugarG: 26,
      proteinG: 3.5,
    }),
    source: {
      name: 'USDA FoodData Central — cake, chocolate, commercially prepared with chocolate frosting',
      url: 'https://fdc.nal.usda.gov/',
    },
    aliases: ['cake'],
  },
  {
    id: 'apple-pie-slice',
    name: 'Apple pie',
    category: 'desserts',
    servingLabel: '1 slice (1/8 of 9-inch pie)',
    increment: 0.5,
    nutrition: n({
      calories: 296,
      totalFatG: 13.8,
      saturatedFatG: 4.7,
      cholesterolMg: 0,
      sodiumMg: 327,
      carbsG: 43,
      fiberG: 1.9,
      totalSugarG: 19.8,
      addedSugarG: 13,
      proteinG: 2.4,
    }),
    source: {
      name: 'USDA FoodData Central — pie, apple, commercially prepared',
      url: 'https://fdc.nal.usda.gov/',
    },
  },
  {
    id: 'cinnamon-roll',
    name: 'Cinnamon roll',
    category: 'desserts',
    servingLabel: '1 roll (with icing)',
    increment: 0.5,
    nutrition: n({
      calories: 310,
      totalFatG: 12,
      saturatedFatG: 3.5,
      cholesterolMg: 10,
      sodiumMg: 340,
      carbsG: 47,
      fiberG: 1,
      totalSugarG: 21,
      addedSugarG: 20,
      proteinG: 5,
    }),
    source: {
      name: 'Typical commercial iced cinnamon roll (restaurant values vary)',
      notes: 'Bakery and chain cinnamon rolls range widely (often 300–880 kcal). This is a modest single-roll estimate, not a Cinnabon Classic.',
    },
  },
  {
    id: 'doritos-nacho',
    name: 'Doritos Nacho Cheese',
    brand: 'Frito-Lay',
    category: 'snacks',
    servingLabel: '1 oz (about 11 chips)',
    increment: 0.5,
    nutrition: n({
      calories: 150,
      totalFatG: 8,
      saturatedFatG: 1,
      sodiumMg: 210,
      carbsG: 18,
      fiberG: 1,
      totalSugarG: 1,
      addedSugarG: 0,
      proteinG: 2,
    }),
    source: {
      name: 'Frito-Lay Doritos Nacho Cheese Nutrition Facts',
      url: 'https://www.doritos.com/',
    },
    aliases: ['doritos', 'chips'],
  },
  {
    id: 'lays-classic',
    name: "Lay's Classic Potato Chips",
    brand: 'Frito-Lay',
    category: 'snacks',
    servingLabel: '1 oz (about 15 chips)',
    increment: 0.5,
    nutrition: n({
      calories: 160,
      totalFatG: 10,
      saturatedFatG: 1.5,
      sodiumMg: 170,
      carbsG: 15,
      fiberG: 1,
      totalSugarG: 0,
      addedSugarG: 0,
      proteinG: 2,
    }),
    source: {
      name: "Frito-Lay Lay's Classic Nutrition Facts",
      url: 'https://www.lays.com/',
    },
    aliases: ['lays', 'potato chips'],
  },
  {
    id: 'cheetos',
    name: 'Cheetos Crunchy',
    brand: 'Frito-Lay',
    category: 'snacks',
    servingLabel: '1 oz (about 21 pieces)',
    increment: 0.5,
    nutrition: n({
      calories: 160,
      totalFatG: 10,
      saturatedFatG: 1.5,
      sodiumMg: 250,
      carbsG: 15,
      fiberG: 1,
      totalSugarG: 1,
      addedSugarG: 0,
      proteinG: 2,
    }),
    source: {
      name: 'Frito-Lay Cheetos Crunchy Nutrition Facts',
      url: 'https://www.cheetos.com/',
    },
  },
  {
    id: 'goldfish',
    name: 'Goldfish Cheddar',
    brand: 'Pepperidge Farm',
    category: 'snacks',
    servingLabel: '55 pieces (30 g)',
    increment: 0.5,
    nutrition: n({
      calories: 140,
      totalFatG: 5,
      saturatedFatG: 1,
      cholesterolMg: 5,
      sodiumMg: 250,
      carbsG: 20,
      fiberG: 1,
      totalSugarG: 0,
      addedSugarG: 0,
      proteinG: 3,
    }),
    source: {
      name: 'Pepperidge Farm Goldfish Cheddar Nutrition Facts',
      url: 'https://www.pepperidgefarm.com/',
    },
    aliases: ['crackers'],
  },
  {
    id: 'cheez-it',
    name: 'Cheez-It Original',
    brand: 'Kellogg',
    category: 'snacks',
    servingLabel: '27 crackers (30 g)',
    increment: 0.5,
    nutrition: n({
      calories: 150,
      totalFatG: 8,
      saturatedFatG: 2,
      cholesterolMg: 5,
      sodiumMg: 230,
      carbsG: 17,
      fiberG: 1,
      totalSugarG: 0,
      addedSugarG: 0,
      proteinG: 3,
    }),
    source: {
      name: 'Cheez-It Original Nutrition Facts',
      url: 'https://www.cheezit.com/',
    },
  },
  {
    id: 'microwave-popcorn',
    name: 'Butter microwave popcorn',
    category: 'snacks',
    servingLabel: '4 cups popped (about 1/3 bag)',
    increment: 0.5,
    nutrition: n({
      calories: 170,
      totalFatG: 12,
      saturatedFatG: 6,
      sodiumMg: 300,
      carbsG: 16,
      fiberG: 3,
      totalSugarG: 0,
      addedSugarG: 0,
      proteinG: 2,
    }),
    source: {
      name: 'Typical butter microwave popcorn label serving',
      notes: 'Brands vary. This matches a common US label serving of about 4 cups popped.',
    },
    aliases: ['popcorn'],
  },
  {
    id: 'pretzels',
    name: 'Pretzels, salted',
    category: 'snacks',
    servingLabel: '1 oz (about 10 twists)',
    increment: 0.5,
    nutrition: n({
      calories: 108,
      totalFatG: 0.8,
      saturatedFatG: 0.2,
      sodiumMg: 385,
      carbsG: 22.7,
      fiberG: 1,
      totalSugarG: 0.8,
      addedSugarG: 0.4,
      proteinG: 2.9,
    }),
    source: {
      name: 'USDA FoodData Central — snacks, pretzels, hard, plain, salted',
      url: 'https://fdc.nal.usda.gov/',
    },
  },
  {
    id: 'pringles',
    name: 'Pringles Original',
    brand: 'Kellogg',
    category: 'snacks',
    servingLabel: '14 chips (28 g)',
    increment: 0.5,
    nutrition: n({
      calories: 150,
      totalFatG: 9,
      saturatedFatG: 2.5,
      sodiumMg: 150,
      carbsG: 15,
      fiberG: 1,
      totalSugarG: 0,
      addedSugarG: 0,
      proteinG: 1,
    }),
    source: {
      name: 'Pringles Original Nutrition Facts',
      url: 'https://www.pringles.com/',
    },
  },
  ...EXTRA_DRINKS,
  ...EXTRA_COOKIES,
  ...EXTRA_CHOCOLATE,
]

export const CATEGORY_META: Record<
  Food['category'],
  { label: string; emoji: string; blurb: string }
> = {
  cookies: { label: 'Cookies', emoji: '🍪', blurb: 'Chain, packaged, and bakery cookies' },
  chocolate_candy: { label: 'Chocolate & candy', emoji: '🍫', blurb: "Hershey's, bars, gummies, chocolate" },
  fast_food: { label: 'Fast food', emoji: '🍟', blurb: 'Burgers, fries, nuggets, pizza' },
  sugary_drinks: { label: 'Soda & drinks', emoji: '🥤', blurb: 'Coke, Diet Coke, and other sodas by mL' },
  desserts: { label: 'Desserts', emoji: '🍦', blurb: 'Ice cream, cake, donuts, pastries' },
  snacks: { label: 'Snacks', emoji: '🍿', blurb: 'Chips, crackers, popcorn' },
  other: { label: 'Other', emoji: '🍽️', blurb: 'Custom and uncategorized foods' },
}
